import click
@click.group()
def cli(): pass
@cli.command()
def status(): click.echo('app_602 running')
@cli.command()
def start(): click.echo('app_602 started')
@cli.command()
def stop(): click.echo('app_602 stopped')
@cli.command()
def restart(): click.echo('app_602 restarted')
@cli.command()
def config(): click.echo('app_602 config')
@cli.command()
def logs(): click.echo('app_602 logs')
if __name__ == '__main__': cli()
