import click
@click.group()
def cli(): pass
@cli.command()
def status(): click.echo('app_571 running')
@cli.command()
def start(): click.echo('app_571 started')
@cli.command()
def stop(): click.echo('app_571 stopped')
@cli.command()
def restart(): click.echo('app_571 restarted')
@cli.command()
def config(): click.echo('app_571 config')
@cli.command()
def logs(): click.echo('app_571 logs')
if __name__ == '__main__': cli()
