import click
@click.group()
def cli(): pass
@cli.command()
def status(): click.echo('app_606 running')
@cli.command()
def start(): click.echo('app_606 started')
@cli.command()
def stop(): click.echo('app_606 stopped')
@cli.command()
def restart(): click.echo('app_606 restarted')
@cli.command()
def config(): click.echo('app_606 config')
@cli.command()
def logs(): click.echo('app_606 logs')
if __name__ == '__main__': cli()
