import click
@click.group()
def cli(): pass
@cli.command()
def status(): click.echo('app_534 running')
@cli.command()
def start(): click.echo('app_534 started')
@cli.command()
def stop(): click.echo('app_534 stopped')
@cli.command()
def restart(): click.echo('app_534 restarted')
@cli.command()
def config(): click.echo('app_534 config')
@cli.command()
def logs(): click.echo('app_534 logs')
if __name__ == '__main__': cli()
