import click
@click.group()
def cli(): pass
@cli.command()
def status(): click.echo('app_644 running')
@cli.command()
def start(): click.echo('app_644 started')
@cli.command()
def stop(): click.echo('app_644 stopped')
@cli.command()
def restart(): click.echo('app_644 restarted')
@cli.command()
def config(): click.echo('app_644 config')
@cli.command()
def logs(): click.echo('app_644 logs')
if __name__ == '__main__': cli()
