import click
@click.group()
def cli(): pass
@cli.command()
def status(): click.echo('app_660 running')
@cli.command()
def start(): click.echo('app_660 started')
@cli.command()
def stop(): click.echo('app_660 stopped')
@cli.command()
def restart(): click.echo('app_660 restarted')
@cli.command()
def config(): click.echo('app_660 config')
@cli.command()
def logs(): click.echo('app_660 logs')
if __name__ == '__main__': cli()
