import click
@click.group()
def cli(): pass
@cli.command()
def status(): click.echo('app_533 running')
@cli.command()
def start(): click.echo('app_533 started')
@cli.command()
def stop(): click.echo('app_533 stopped')
@cli.command()
def restart(): click.echo('app_533 restarted')
@cli.command()
def config(): click.echo('app_533 config')
@cli.command()
def logs(): click.echo('app_533 logs')
if __name__ == '__main__': cli()
