import click
@click.group()
def cli(): pass
@cli.command()
def status(): click.echo('app_524 running')
@cli.command()
def start(): click.echo('app_524 started')
@cli.command()
def stop(): click.echo('app_524 stopped')
@cli.command()
def restart(): click.echo('app_524 restarted')
@cli.command()
def config(): click.echo('app_524 config')
@cli.command()
def logs(): click.echo('app_524 logs')
if __name__ == '__main__': cli()
