import click
@click.group()
def cli(): pass
@cli.command()
def status(): click.echo('app_538 running')
@cli.command()
def start(): click.echo('app_538 started')
@cli.command()
def stop(): click.echo('app_538 stopped')
@cli.command()
def restart(): click.echo('app_538 restarted')
@cli.command()
def config(): click.echo('app_538 config')
@cli.command()
def logs(): click.echo('app_538 logs')
if __name__ == '__main__': cli()
