import click
@click.group()
def cli(): pass
@cli.command()
def status(): click.echo('app_580 running')
@cli.command()
def start(): click.echo('app_580 started')
@cli.command()
def stop(): click.echo('app_580 stopped')
@cli.command()
def restart(): click.echo('app_580 restarted')
@cli.command()
def config(): click.echo('app_580 config')
@cli.command()
def logs(): click.echo('app_580 logs')
if __name__ == '__main__': cli()
