import click
@click.group()
def cli(): pass
@cli.command()
def status(): click.echo('app_531 running')
@cli.command()
def start(): click.echo('app_531 started')
@cli.command()
def stop(): click.echo('app_531 stopped')
@cli.command()
def restart(): click.echo('app_531 restarted')
@cli.command()
def config(): click.echo('app_531 config')
@cli.command()
def logs(): click.echo('app_531 logs')
if __name__ == '__main__': cli()
